### ISSUE TITLE
commons-math-2.2 is recognized as annotation processor

### ISSUE THREAD

**Issue by michaldo** [jbosstools/m2e-apt#54] opened 2016-06-09 09:40 UTC
When I import Maven project with commons-math-2.2 the library is recognized as annotation processor and registered in .factorypath file.
I scanned source files and I don't see any *Processor in math-2.2

Steps to reproduce: Import project https://github.com/michaldo/m2e-apt-problem2

### Environment:

Eclipse Mars 4.5.2
Maven Integration for Eclipse JDT APT 1.3.0.201606081857
Window>Preferences>Maven>Annotation Processing>Automaticaly configure JDT...

**Comment by fbricon** [comment] 2016-06-09 12:28
This is a duplicate of #13.

**Closed by fbricon** 2016-06-09 12:28 UTC
Labels: duplicate

**Comment by michaldo** [comment] 2016-06-09 13:01
I'm afraid it is unclear to me. I expect math-2-2 is NOT registered in .factorypath, but actually is.
If my expectation is correct then issue should be open. If my expectation is wrong please explain me my mistake

**Comment by fbricon** [comment] 2016-06-09 13:05
This is a known issue (see #13), hence closed as duplicate. Basically the problem is all project dependencies are currently added to the factorypath because, in some cases, ClassNotFoundExceptions could be thrown if some of these non-AP dependencies were missing.
